export const businessConfig = {
  brand: {
    nameLocal: 'لارا للجمال',
    nameEnglish: 'LARA BEAUTY',
    tagline: 'علكات يومية تدعم جسمك من الداخل',
    description:
      'علكات لارا — تركيبات مدروسة للنوم، الطاقة، والتركيز. دفع عند الاستلام داخل الإمارات.',
    logoUrl: '/images/logo-header.webp',
    logoIconUrl: '/images/logo-icon.webp',
    logoWhiteUrl: '/images/logo-white.webp',
    iconUrl: '/images/logo-icon.webp',
  },
  market: {
    countryName: 'الإمارات',
    countryCode: 'AE',
    language: 'ar',
    direction: 'rtl' as const,
    currency: 'AED',
    currencySymbol: 'د.إ',
    currencyName: 'درهم إماراتي',
    phoneCountryCode: '+971',
    phoneExample: '501234567',
    emirates: [
      'دبي',
      'أبوظبي',
      'الشارقة',
      'عجمان',
      'رأس الخيمة',
      'الفجيرة',
      'أم القيوين',
      'العين',
    ],
  },
  cod: {
    enabled: true,
    paymentLabel: 'الدفع عند الاستلام',
    deliveryPromise: 'توصيل 2–4 أيام عمل لكل إمارات الدولة',
    confirmationPromise: 'فريقنا يتصل فيك خلال ساعات لتأكيد العنوان',
    confirmationWindow: 'خلال ساعتين في أوقات العمل',
    returnGuarantee: 'ضمان استرجاع 30 يوم — فلوسك ترجع إذا ما عجبك الروتين',
    cashReminder: 'جهّزي المبلغ كاش أو بطاقة عند الاستلام',
  },
  payment: {
    /** Set NEXT_PUBLIC_CARD_PAYMENT_ENABLED=true in EasyPanel when Stripe backend is live */
    cardEnabled: process.env.NEXT_PUBLIC_CARD_PAYMENT_ENABLED === 'true',
    codDeliveryFeeAed: 20,
    freeDeliveryLabel: 'مجاني',
    cardTitle: 'الدفع بالبطاقة',
    cardSubtitle: 'شحن مجاني',
    cardHint: 'دفع آمن عبر Stripe',
    codTitle: 'الدفع عند الاستلام',
    codSubtitle: '+20 د.إ رسوم التوصيل',
    codHint: 'تدفعين عند استلام الطلب',
    selectorTitle: 'اختر طريقة الدفع',
    cardCtaPrefix: 'الدفع بالبطاقة الآن',
    codCtaPrefix: 'تأكيد الطلب',
    cardPopularBadge: 'الأكثر اختياراً',
    cardRedirectNote: 'ستتم تحويلك إلى صفحة الدفع الآمنة الخاصة بـ Stripe',
    codFormNote: 'نتصل بيك لتأكيد العنوان — الاسم والجوال فقط مطلوبين الآن',
    cardLoadingLabel: 'جارٍ إتمام الدفع...',
    codLoadingLabel: 'جارٍ تأكيد الطلب...',
    securePayment: 'دفع آمن',
    secureStripe: 'بيانات الدفع تتم معالجتها بأمان عبر Stripe',
    noCardStorage: 'لا نحتفظ ببيانات بطاقتك',
    codDeliveryNote: 'رسوم التوصيل 20 د.إ',
  },
  checkout: {
    pageSubtitle: 'اختر طريقة الدفع المناسبة لك',
    summaryTitle: 'ملخص الطلب',
    subtotalLabel: 'المجموع الفرعي',
    deliveryLabel: 'التوصيل',
    totalLabel: 'المجموع',
    grandTotalLabel: 'المجموع الكلي',
    codFormTitle: 'معلومات التواصل',
    cardFormTitle: 'معلومات التوصيل',
    nameLabel: 'الاسم الكامل',
    namePlaceholder: 'مثال: نورة العتيبي',
    phoneLabel: 'رقم الهاتف',
    phonePlaceholder: '0501234567',
    phoneHint: 'رقم جوال إماراتي صحيح لتأكيد التوصيل',
    areaLabel: 'المنطقة',
    areaPlaceholder: 'اختاري الإمارة',
    addressLabel: 'العنوان / تفاصيل التوصيل',
    addressPlaceholder: 'مثال: دبي مارينا، برج السكن، شقة 1204',
    termsNote: 'بالمتابعة أنتِ توافقين على الشروط والأحكام وسياسة الخصوصية',
    trustCallConfirm: 'نتصل للتأكيد',
    trustDelivery: 'توصيل داخل الإمارات',
    trustSecure: 'دفع آمن',
  },
  support: {
    /** رقم واتساب بدون + أو مسافات — wa.me */
    whatsappNumber: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER ?? '12402107635',
    whatsappDisplay: process.env.NEXT_PUBLIC_WHATSAPP_DISPLAY ?? '+1 (240) 210-7635',
    phoneDisplay: process.env.NEXT_PUBLIC_SUPPORT_PHONE ?? '+1 (240) 210-7635',
    email: process.env.NEXT_PUBLIC_SUPPORT_EMAIL ?? 'support@larabeauty.store',
    hours: 'يومياً 9 ص — 10 م',
  },
  social: {
    tiktok: 'https://www.tiktok.com/@lara_beauty_gcc',
    tiktokHandle: '@lara_beauty_gcc',
    facebook: 'https://www.facebook.com/profile.php?id=61592789362233',
    facebookLabel: 'لارا للجمال على فيسبوك',
    instagram: 'https://www.instagram.com/lara_beauty_gcc',
    instagramHandle: '@lara_beauty_gcc',
  },
  design: {
    primaryColor: '#134E3A',
    primaryDarkColor: '#0F3D2E',
    accentColor: '#C8A55C',
    backgroundColor: '#FBF8F2',
    cardColor: '#FFFFFF',
    textColor: '#1A2E22',
    mutedTextColor: '#5F6B62',
    borderColor: '#E5DFCD',
    primarySoftColor: '#E8EFE9',
    secondarySoftColor: '#F5EDD8',
    surfaceRoseColor: '#F5F0E5',
    themeColor: '#134E3A',
  },
};

/** @deprecated use businessConfig — kept for existing imports */
export const businessInputs = businessConfig;
