export const businessConfig = {
  brand: {
    nameLocal: 'لارا للجمال',
    nameEnglish: 'LARA BEAUTY',
    tagline: 'علكات يومية تدعم جسمك من الداخل',
    description:
      'علكات لارا — تركيبات مدروسة للنوم، الطاقة، والتركيز. دفع عند الاستلام داخل الإمارات.',
    logoUrl: '/images/logo-header.webp',
    logoIconUrl: '/images/logo-icon.webp',
    logoWhiteUrl: '/images/logo-white.webp',
    iconUrl: '/images/logo-icon.webp',
  },
  market: {
    countryName: 'الإمارات',
    countryCode: 'AE',
    language: 'ar',
    direction: 'rtl' as const,
    currency: 'AED',
    currencySymbol: 'د.إ',
    currencyName: 'درهم إماراتي',
    phoneCountryCode: '+971',
    phoneExample: '501234567',
    emirates: [
      'دبي',
      'أبوظبي',
      'الشارقة',
      'عجمان',
      'رأس الخيمة',
      'الفجيرة',
      'أم القيوين',
      'العين',
    ],
  },
  cod: {
    enabled: true,
    paymentLabel: 'دفع عند الاستلام — بدون دفع أونلاين',
    deliveryPromise: 'توصيل 2–4 أيام عمل لكل إمارات الدولة',
    confirmationPromise: 'فريقنا يتصل فيك خلال ساعات لتأكيد العنوان',
    confirmationWindow: 'خلال ساعتين في أوقات العمل',
    returnGuarantee: 'ضمان استرجاع 30 يوم — فلوسك ترجع إذا ما عجبك الروتين',
    cashReminder: 'جهّزي المبلغ كاش أو بطاقة عند الاستلام',
  },
  support: {
  /** رقم واتساب بدون + أو مسافات — مثال: 971501234567 */
    whatsappNumber: process.env.NEXT_PUBLIC_WHATSAPP_NUMBER ?? '971501234567',
    phoneDisplay: process.env.NEXT_PUBLIC_SUPPORT_PHONE ?? '+971 50 123 4567',
    email: process.env.NEXT_PUBLIC_SUPPORT_EMAIL ?? 'support@larabeauty.store',
    hours: 'يومياً 9 ص — 10 م',
  },
  social: {
    tiktok: 'https://www.tiktok.com/@lara_beauty_gcc',
    tiktokHandle: '@lara_beauty_gcc',
    facebook: 'https://www.facebook.com/profile.php?id=61592789362233',
    facebookLabel: 'لارا للجمال على فيسبوك',
    instagram: 'https://www.instagram.com/lara_beauty_gcc',
    instagramHandle: '@lara_beauty_gcc',
  },
  design: {
    primaryColor: '#134E3A',
    primaryDarkColor: '#0F3D2E',
    accentColor: '#C8A55C',
    backgroundColor: '#FBF8F2',
    cardColor: '#FFFFFF',
    textColor: '#1A2E22',
    mutedTextColor: '#5F6B62',
    borderColor: '#E5DFCD',
    primarySoftColor: '#E8EFE9',
    secondarySoftColor: '#F5EDD8',
    surfaceRoseColor: '#F5F0E5',
    themeColor: '#134E3A',
  },
};

/** @deprecated use businessConfig — kept for existing imports */
export const businessInputs = businessConfig;
